mode: rule
port: 7892
mixed-port: 7890
socks-port: 7891
redir-port: 7893
allow-lan: true
log-level: info
external-controller: :9090
dns:
  enable: true
  ipv6: false
  listen: :53
  prefer-h3: true
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - '*.local'
    - '*.internal'
    - 'dns.msftncsi.com'
    - 'www.msftncsi.com'
    - 'www.msftconnecttest.com'
    - 'ipv6.msftconnecttest.com'
    - 'localhost.ptlogin2.qq.com'
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  nameserver-policy:
    'geosite:cn':
      - 119.29.29.29
      - 223.5.5.5
  nameserver:
    - https://120.53.53.53/dns-query
    - https://223.5.5.5/dns-query
  proxy-server-nameserver:
    - https://120.53.53.53/dns-query
    - https://223.5.5.5/dns-query
  fallback:
    - https://1.1.1.1/dns-query
    - https://8.8.8.8/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - gfw
    ipcidr:
      - 240.0.0.0/4
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - 'Mijia Cloud'
    - '+.push.apple.com'
